name: needle_window
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.3
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.0
  - python=3.9.19
  - readline=8.2
  - setuptools=70.0.0
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - anyio==4.4.0
    - asgiref==3.8.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - backoff==2.2.1
    - bcrypt==4.1.3
    - beautifulsoup4==4.12.3
    - bidict==0.23.1
    - blinker==1.8.2
    - bs4==0.0.2
    - build==1.2.1
    - cachetools==5.3.3
    - certifi==2024.6.2
    - charset-normalizer==3.3.2
    - chroma-hnswlib==0.7.3
    - chromadb==0.5.0
    - click==8.1.7
    - coloredlogs==15.0.1
    - dataclasses-json==0.6.6
    - deprecated==1.2.14
    - dnspython==2.6.1
    - email-validator==2.1.1
    - evdev==1.7.1
    - exceptiongroup==1.2.1
    - fastapi==0.111.0
    - fastapi-cli==0.0.4
    - filelock==3.14.0
    - flask==3.0.3
    - flask-cors==4.0.1
    - flask-socketio==5.3.6
    - flatbuffers==24.3.25
    - frozenlist==1.4.1
    - fsspec==2024.6.0
    - google-auth==2.29.0
    - googleapis-common-protos==1.63.1
    - greenlet==3.0.3
    - grpcio==1.64.1
    - h11==0.14.0
    - httpcore==1.0.5
    - httptools==0.6.1
    - httpx==0.27.0
    - huggingface-hub==0.23.2
    - humanfriendly==10.0
    - idna==3.7
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.0
    - itsdangerous==2.2.0
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonpatch==1.33
    - jsonpointer==2.4
    - kubernetes==29.0.0
    - langchain==0.2.1
    - langchain-community==0.2.1
    - langchain-core==0.2.3
    - langchain-text-splitters==0.2.1
    - langsmith==0.1.71
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - marshmallow==3.21.2
    - mdurl==0.1.2
    - mmh3==4.1.0
    - monotonic==1.6
    - mpmath==1.3.0
    - multidict==6.0.5
    - mypy-extensions==1.0.0
    - networkx==3.2.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.5.40
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - onnxruntime==1.18.0
    - opentelemetry-api==1.25.0
    - opentelemetry-exporter-otlp-proto-common==1.25.0
    - opentelemetry-exporter-otlp-proto-grpc==1.25.0
    - opentelemetry-instrumentation==0.46b0
    - opentelemetry-instrumentation-asgi==0.46b0
    - opentelemetry-instrumentation-fastapi==0.46b0
    - opentelemetry-proto==1.25.0
    - opentelemetry-sdk==1.25.0
    - opentelemetry-semantic-conventions==0.46b0
    - opentelemetry-util-http==0.46b0
    - orjson==3.10.3
    - overrides==7.7.0
    - packaging==23.2
    - pillow==10.3.0
    - posthog==3.5.0
    - protobuf==4.25.3
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pydantic==2.7.3
    - pydantic-core==2.18.4
    - pygments==2.18.0
    - pynput==1.7.7
    - pypdf2==3.0.1
    - pypika==0.48.9
    - pyproject-hooks==1.1.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-engineio==4.9.1
    - python-multipart==0.0.9
    - python-socketio==5.11.2
    - python-xlib==0.33
    - pyyaml==6.0.1
    - regex==2024.5.15
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rich==13.7.1
    - safetensors==0.4.3
    - scikit-learn==1.5.0
    - scipy==1.13.1
    - sentence-transformers==3.0.0
    - shellingham==1.5.4
    - simple-websocket==1.0.0
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.5
    - sqlalchemy==2.0.30
    - starlette==0.37.2
    - sympy==1.12.1
    - tenacity==8.3.0
    - threadpoolctl==3.5.0
    - tokenizers==0.19.1
    - tomli==2.0.1
    - torch==2.2.0
    - tqdm==4.66.4
    - transformers==4.41.2
    - triton==2.2.0
    - typer==0.12.3
    - typing-extensions==4.12.1
    - typing-inspect==0.9.0
    - ujson==5.10.0
    - urllib3==2.2.1
    - uvicorn==0.30.1
    - uvloop==0.19.0
    - watchfiles==0.22.0
    - websocket-client==1.8.0
    - websockets==12.0
    - werkzeug==3.0.3
    - wrapt==1.16.0
    - wsproto==1.2.0
    - yarl==1.9.4
    - zipp==3.19.2
